package com.guc.fileuploadtest.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.guc.fileuploadtest.bean.BeanWaitUpload;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BEAN_WAIT_UPLOAD".
*/
public class BeanWaitUploadDao extends AbstractDao<BeanWaitUpload, Long> {

    public static final String TABLENAME = "BEAN_WAIT_UPLOAD";

    /**
     * Properties of entity BeanWaitUpload.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property _id = new Property(0, Long.class, "_id", true, "_id");
        public final static Property Paths = new Property(1, String.class, "paths", false, "PATHS");
        public final static Property Params = new Property(2, String.class, "params", false, "PARAMS");
        public final static Property IsUpload = new Property(3, boolean.class, "isUpload", false, "IS_UPLOAD");
    }


    public BeanWaitUploadDao(DaoConfig config) {
        super(config);
    }
    
    public BeanWaitUploadDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BEAN_WAIT_UPLOAD\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: _id
                "\"PATHS\" TEXT," + // 1: paths
                "\"PARAMS\" TEXT," + // 2: params
                "\"IS_UPLOAD\" INTEGER NOT NULL );"); // 3: isUpload
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BEAN_WAIT_UPLOAD\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, BeanWaitUpload entity) {
        stmt.clearBindings();
 
        Long _id = entity.get_id();
        if (_id != null) {
            stmt.bindLong(1, _id);
        }
 
        String paths = entity.getPaths();
        if (paths != null) {
            stmt.bindString(2, paths);
        }
 
        String params = entity.getParams();
        if (params != null) {
            stmt.bindString(3, params);
        }
        stmt.bindLong(4, entity.getIsUpload() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, BeanWaitUpload entity) {
        stmt.clearBindings();
 
        Long _id = entity.get_id();
        if (_id != null) {
            stmt.bindLong(1, _id);
        }
 
        String paths = entity.getPaths();
        if (paths != null) {
            stmt.bindString(2, paths);
        }
 
        String params = entity.getParams();
        if (params != null) {
            stmt.bindString(3, params);
        }
        stmt.bindLong(4, entity.getIsUpload() ? 1L: 0L);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public BeanWaitUpload readEntity(Cursor cursor, int offset) {
        BeanWaitUpload entity = new BeanWaitUpload( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // _id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // paths
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // params
            cursor.getShort(offset + 3) != 0 // isUpload
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, BeanWaitUpload entity, int offset) {
        entity.set_id(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPaths(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setParams(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setIsUpload(cursor.getShort(offset + 3) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(BeanWaitUpload entity, long rowId) {
        entity.set_id(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(BeanWaitUpload entity) {
        if(entity != null) {
            return entity.get_id();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(BeanWaitUpload entity) {
        return entity.get_id() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
