package com.guc.fileuploadtest.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.guc.fileuploadtest.bean.BeanWaitUpload;

import com.guc.fileuploadtest.greendao.BeanWaitUploadDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig beanWaitUploadDaoConfig;

    private final BeanWaitUploadDao beanWaitUploadDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        beanWaitUploadDaoConfig = daoConfigMap.get(BeanWaitUploadDao.class).clone();
        beanWaitUploadDaoConfig.initIdentityScope(type);

        beanWaitUploadDao = new BeanWaitUploadDao(beanWaitUploadDaoConfig, this);

        registerDao(BeanWaitUpload.class, beanWaitUploadDao);
    }
    
    public void clear() {
        beanWaitUploadDaoConfig.clearIdentityScope();
    }

    public BeanWaitUploadDao getBeanWaitUploadDao() {
        return beanWaitUploadDao;
    }

}
